"""Adiciona tabelas para RFQ Aberto e anexos no chat

Revision ID: 76d6f5bf1e81
Revises: 2062d7aa6967
Create Date: 2025-10-31 13:58:27.136884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d6f5bf1e81'
down_revision = '2062d7aa6967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_rfq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_rfq_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['open_rfq.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attachment_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('attachment_type')
        batch_op.drop_column('attachment_filename')

    op.drop_table('open_rfq_response')
    op.drop_table('open_rfq')
    # ### end Alembic commands ###
